<script setup>
import {computed,reactive,watch} from 'vue';import {concurrencyMechanisms} from '../sim/models/concurrency.mjs';import {finalDefaults,simulateFinal,incidentById} from '../sim/final-integrated.mjs';
const props=defineProps({incidentId:String});const state=reactive({});function load(id){Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,structuredClone(finalDefaults[id]||{}))}watch(()=>props.incidentId,load,{immediate:true});
const incident=computed(()=>incidentById(props.incidentId));const r=computed(()=>simulateFinal(props.incidentId,state));
</script><template><section class="final-sim"><header><span>INTEGRATED SYSTEM · INCIDENT</span><h2>{{incident.title}}</h2><p>{{incident.question}}</p></header><div class="final-system"><b>Case UI</b><i>→</i><b>Backend / Workflow</b><i>→</i><b>Document Queue + Worker</b><i>→</i><b>Database / Artifact</b><i>→</i><b>Notification</b></div>
<section v-if="incidentId==='concurrent'" class="sim-lab"><div class="sim-controls"><div><span>同時更新</span><div class="sim-segment"><button v-for="n in [1,2,5]" :key="n" :aria-pressed="state.writers===n" @click="state.writers=n">{{n}} workers</button></div></div><div><span>案件狀態保護</span><div class="sim-segment"><button v-for="(m,id) in concurrencyMechanisms" :key="id" :aria-pressed="state.mechanism===id" @click="state.mechanism=id">{{m.label}}</button></div></div></div><div class="sim-metrics"><div><span>成功更新</span><strong>{{r.accepted}}</strong></div><div><span>衝突拒絕</span><strong>{{r.rejected}}</strong></div><div :class="{'is-bad':r.invalid}"><span>不合法狀態</span><strong>{{r.invalid}}</strong></div><div><span>等待</span><strong>{{r.waitMs}} ms</strong></div></div></section>
<section v-else-if="incidentId==='backlog'" class="sim-lab"><div class="sim-controls"><div><span>文件工作：{{state.arrival}}/s</span><input v-model.number="state.arrival" type="range" min="200" max="2000" step="100"></div><div><span>Workers</span><div class="sim-segment"><button v-for="n in [1,2,4]" :key="n" :aria-pressed="state.workers===n" @click="state.workers=n">{{n}}</button></div></div></div><div class="sim-metrics"><div><span>Capacity</span><strong>{{r.capacity}}/s</strong></div><div :class="{'is-bad':r.queueDepth}"><span>10 秒 backlog</span><strong>{{r.queueDepth}}</strong></div><div><span>Queue age</span><strong>{{r.queueAge.toFixed(1)}}s</strong></div><div><span>完成</span><strong>{{r.processedPerSec}}/s</strong></div></div></section>
<section v-else-if="incidentId==='unknown'||incidentId==='provider'" class="sim-lab"><div class="sim-controls"><div><span>Timeout：{{Math.round(state.timeoutRate*100)}}%</span><input v-model.number="state.timeoutRate" type="range" min="0" max=".2" step=".01"></div><div><span>Retry</span><div class="sim-segment"><button v-for="n in [0,1,3]" :key="n" :aria-pressed="state.retries===n" @click="state.retries=n">{{n}}</button></div></div><div><span>安全措施</span><div class="sim-segment"><button :aria-pressed="state.verify" @click="state.verify=!state.verify">先查證</button><button :aria-pressed="state.idempotency" @click="state.idempotency=!state.idempotency">冪等</button></div></div></div><div class="sim-metrics"><div><span>Provider calls</span><strong>{{r.providerLoad}}</strong></div><div><span>查證</span><strong>{{r.verifiedBeforeRetry}}</strong></div><div :class="{'is-bad':r.duplicateEffects}"><span>重複效果</span><strong>{{r.duplicateEffects}}</strong></div><div :class="{'is-bad':r.unknown}"><span>Unknown</span><strong>{{r.unknown}}</strong></div></div></section>
<section v-else-if="incidentId==='version'" class="sim-lab"><div class="sim-controls"><div><span>v2 rollout：{{state.rollout}}%</span><input v-model.number="state.rollout" type="range" min="0" max="100" step="10"></div><div><span>Contract</span><div class="sim-segment"><button :aria-pressed="state.compatibility" @click="state.compatibility=true">相容</button><button :aria-pressed="!state.compatibility" @click="state.compatibility=false">不相容</button></div></div><div><span>DB</span><div class="sim-segment"><button :aria-pressed="state.schema==='expanded'" @click="state.schema='expanded'">old + new</button><button :aria-pressed="state.schema==='contracted'" @click="state.schema='contracted'">new only</button></div></div></div><div class="sim-metrics"><div><span>v2 exposure</span><strong>{{r.blastRadius}}%</strong></div><div :class="{'is-bad':r.affectedTraffic}"><span>受影響</span><strong>{{r.affectedTraffic}}%</strong></div><div><span>v1 在線</span><strong>{{r.oldPct}}%</strong></div><div :class="{'is-bad':!r.rollbackSafe}"><span>Rollback</span><strong>{{r.rollbackSafe?'可相容':'不安全'}}</strong></div></div></section>
<div class="sim-consequence"><strong>這裡沒有章節提示，也沒有唯一按鈕答案。</strong><p>先改一個控制項，觀察哪個 state / metric 跟著變，再決定下一個動作。你用的是前八章同一組推理工具。</p></div></section></template>