import test from 'node:test';
import assert from 'node:assert/strict';
import {labs,simulate,frameAt,cleanConfig,readLabs,labMarkdown} from '../learning/system-lab.mjs';
function combinations(options,i=0,c={}){if(i===options.length)return [c];return options[i].choices.flatMap(v=>combinations(options,i+1,{...c,[options[i].key]:v.value}));}
test('all seven graph experiments terminate with valid events for every configuration',()=>{for(const [id,lab]of Object.entries(labs)){for(const c of combinations(lab.options)){const r=simulate(id,c);assert(r.events.length>0&&r.events.length<15);const ids=lab.nodes.map(n=>n.id);for(const e of r.events){assert(ids.includes(e.from)&&ids.includes(e.to));for(const k of Object.keys(e.patch))assert(ids.includes(k));}assert.equal(frameAt(id,r,r.events.length).result,r.outcome);assert.deepEqual(r,simulate(id,c));for(const v of Object.values(r.metrics))assert(Number.isFinite(v)&&v>=0);}assert(simulate(id,lab.good).pass,id);}});
test('lost response preserves write; only new creation duplicates reminder',()=>{const r=simulate('reliability',{response:'lost',recovery:'retry'});const lost=r.events.findIndex(e=>e.kind==='lost');assert.match(frameAt('reliability',r,lost+1).data,/R1/);assert(!frameAt('reliability',r,lost+1).data.includes('R2'));assert.equal(r.metrics.提醒張數,2);for(const recovery of ['lookup','key'])assert.equal(simulate('reliability',{response:'lost',recovery}).metrics.提醒張數,1);assert(!frameAt('reliability',r,0).data.includes('R1'));});
test('required evidence and authorization cannot be bypassed by adding disconnected labels',()=>{assert(!simulate('overview',{guard:'off',permission:'read'}).pass);assert(!simulate('overview',{guard:'on',permission:'all'}).pass);assert(simulate('overview',labs.overview.good).pass);const r=simulate('evidence',{a:'receipt',b:'receipt',verify:'on'});assert(!r.pass);assert.equal(r.metrics.交付錯誤句子,0);assert.equal(r.metrics.不受支持句子,1);});
test('capacity, freshness, dependency and handoff change actual outcomes',()=>{assert(!simulate('context',{...labs.context.good,chat:'yes'}).pass);assert(!simulate('context',{...labs.context.good,receipt:'old'}).pass);assert.equal(simulate('optimization',labs.optimization.good).metrics.完成秒數,4);assert.equal(simulate('optimization',{schedule:'serial',dependency:'yes'}).metrics.完成秒數,6);assert(!simulate('optimization',{schedule:'parallel',dependency:'yes'}).pass);assert(!simulate('multi',{...labs.multi.good,source:'no'}).pass);assert.match(simulate('multi',{...labs.multi.good,failure:'yes'}).outcome,/尚未完成/);assert.equal(simulate('loop',{checkpoint:'on',fresh:'changed'}).metrics.案件查詢次數,2);});
test('saved experiments normalize unsafe input and reproduce exported results',()=>{assert.deepEqual(readLabs('bad'),{});assert.deepEqual(readLabs('{"version":3}'),{});const entries={reliability:labs.reliability.good};assert.deepEqual(readLabs(JSON.stringify({version:4,entries})),entries);assert.deepEqual(cleanConfig('overview',{guard:'malicious'}),labs.overview.defaults);assert.match(labMarkdown(entries),/提醒張數：1/);});
