import {simulateEvidence} from '../learning/v2/sim/models/evidence.mjs';
import {simulateRollout} from '../learning/v2/sim/models/rollout.mjs';
import {simulateQueue} from '../learning/v2/sim/models/queue.mjs';
import {simulateFailure} from '../learning/v2/sim/models/failure.mjs';
import {simulateConcurrency} from '../learning/v2/sim/models/concurrency.mjs';
import {simulateCapacity} from '../learning/v2/sim/models/capacity.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {units,unitById,stageById} from '../learning/v2/course.mjs';import {parseV2Route,v2Route,choose,finalIncident} from '../learning/v2/interaction.mjs';
test('v2 keeps eight system-design questions',()=>{assert.equal(units.length,8);assert.deepEqual(units.map(u=>u.number),[1,2,3,4,5,6,7,8]);});
test('first slice has interactive units 1 and 2',()=>{assert.ok(unitById('requirements').stages.length>=3);assert.ok(unitById('boundaries').stages.length>=4);});
test('v2 route resolves map and stage',()=>{assert.deepEqual(parseV2Route('#/v2'),{view:'map'});assert.deepEqual(parseV2Route(v2Route('requirements','rule')),{view:'unit',unit:'requirements',stage:'rule'});});
test('unknown stage falls back deterministically',()=>{assert.equal(stageById(unitById('requirements'),'missing').id,'enough');});
test('choice reveals feedback and optional term',()=>{const stage=stageById(unitById('requirements'),'enough');const result=choose(stage,0);assert.match(result.feedback,/規則/);assert.match(result.term.name,/Constraint/);});
test('invalid choice does not invent state',()=>{assert.equal(choose(stageById(unitById('requirements'),'enough'),99),null);});
test('units 3 to 5 expose the intended reasoning progression',()=>{assert.deepEqual(['concurrency','async','failure'].map(id=>unitById(id).stages.length),[4,4,4]);assert.equal(stageById(unitById('failure'),'timeout').term.name.startsWith('Unknown outcome'),true);});
test('transfer stages do not name the solution in their prompt',()=>{for(const id of ['concurrency','async','failure']){const s=stageById(unitById(id),'transfer');assert.ok(s);assert.doesNotMatch(s.prompt,/Redis|transaction|queue|idempotency/i);}});

test('all eight units now have learner-facing stages',()=>{for(const unit of units)assert.ok(unit.stages.length>=3,`${unit.id} has too few stages`);});
test('units 6 to 8 end with unprompted transfer practice',()=>{for(const id of ['evidence','scale','evolution'])assert.equal(unitById(id).stages.at(-1).id,'transfer');});
test('final transfer route and incidents are deterministic',()=>{assert.equal(parseV2Route('#/v2/final').view,'final');assert.equal(finalIncident('unknown').id,'unknown');assert.equal(finalIncident('missing').id,'concurrent');});
test('core first-use terms include plain-language definitions',()=>{for(const unit of units){for(const stage of unit.stages){if(stage.term){assert.ok(stage.term.name.length>2);assert.ok(stage.term.plain.length>8);}}}});

test('concurrency simulator makes invariant break observable',()=>{const unsafe=simulateConcurrency({capacity:1,writers:2,mechanism:'none'});assert.equal(unsafe.invalid,1);assert.equal(unsafe.ruleHeld,false);const safe=simulateConcurrency({capacity:1,writers:2,mechanism:'constraint'});assert.equal(safe.invalid,0);assert.equal(safe.rejected,1);});
test('locking trades correctness for visible waiting in the teaching model',()=>{const r=simulateConcurrency({capacity:1,writers:5,mechanism:'lock'});assert.equal(r.ruleHeld,true);assert.ok(r.waitMs>0);});
test('capacity simulator exposes database bottleneck and cache consequence',()=>{const base=simulateCapacity({preset:'url',requestsPerSec:20000,cache:false});assert.ok(base.bottlenecks.includes('db'));const cached=simulateCapacity({preset:'url',requestsPerSec:20000,cache:true,cacheHit:.85});const db=cached.nodes.find(n=>n.id==='db');assert.ok(db.incoming<base.nodes.find(n=>n.id==='db').incoming);});
test('video CDN changes origin bandwidth rather than pretending request work vanished',()=>{const base=simulateCapacity({preset:'video',requestsPerSec:10000,cdn:false,objectKB:5000,cacheHit:.9});const edge=simulateCapacity({preset:'video',requestsPerSec:10000,cdn:true,objectKB:5000,cacheHit:.9});assert.ok(edge.bandwidthMbps<base.bandwidthMbps);});

test('async queue separates response latency from completion and exposes backlog',()=>{const sync=simulateQueue({arrivalRate:800,workerRate:400,workers:1,async:false});const asyncRun=simulateQueue({arrivalRate:800,workerRate:400,workers:1,async:true});assert.ok(asyncRun.requestLatency<sync.requestLatency);assert.ok(asyncRun.queueDepth>0);assert.ok(asyncRun.completionLatency>asyncRun.requestLatency);});
test('more workers reduce queue backlog when capacity catches up',()=>{const one=simulateQueue({arrivalRate:800,workerRate:400,workers:1,async:true});const two=simulateQueue({arrivalRate:800,workerRate:400,workers:2,async:true});assert.ok(two.queueDepth<one.queueDepth);assert.equal(two.queueDepth,0);});
test('blind retries increase provider load and can duplicate effects',()=>{const base=simulateFailure({operations:1000,timeoutRate:.1,retries:0});const retry=simulateFailure({operations:1000,timeoutRate:.1,retries:3,idempotency:false});assert.ok(retry.providerLoad>base.providerLoad);assert.ok(retry.duplicateEffects>0);});
test('idempotency removes duplicate effects without pretending unknown outcomes vanish',()=>{const r=simulateFailure({operations:1000,timeoutRate:.1,retries:1,idempotency:true});assert.equal(r.duplicateEffects,0);assert.ok(r.unknown>=0);});
test('verification before retry reduces blind retry candidates and provider load',()=>{const blind=simulateFailure({operations:1000,timeoutRate:.1,retries:1,verifyBeforeRetry:false});const verify=simulateFailure({operations:1000,timeoutRate:.1,retries:1,verifyBeforeRetry:true});assert.ok(verify.providerLoad<blind.providerLoad);assert.ok(verify.verifiedBeforeRetry>0);});

test('evidence views expose different slices of the same failure',()=>{const log=simulateEvidence({failure:'worker-crash',view:'log'});const trace=simulateEvidence({failure:'worker-crash',view:'trace'});const state=simulateEvidence({failure:'worker-crash',view:'state'});assert.notDeepEqual(log.items,trace.items);assert.match(trace.items.join(' '),/Worker/);assert.match(state.items.join(' '),/artifact = missing/);});
test('rollout limits exposure but cannot repair incompatibility',()=>{const ten=simulateRollout({rollout:10,compatibility:false,schema:'expanded'});const full=simulateRollout({rollout:100,compatibility:false,schema:'expanded'});assert.ok(ten.affectedTraffic>0);assert.ok(full.blastRadius>ten.blastRadius);assert.equal(full.canPromote,false);});
test('contracting schema while old version exists makes rollback unsafe',()=>{const safe=simulateRollout({rollout:50,compatibility:true,schema:'expanded'});const unsafe=simulateRollout({rollout:50,compatibility:true,schema:'contracted'});assert.equal(safe.rollbackSafe,true);assert.equal(unsafe.rollbackSafe,false);assert.ok(unsafe.incompatibleOldTraffic>0);});
