<script setup>
import { ref, computed, onUnmounted } from 'vue';
import { workflow, calls, sources, sourceTotals, totals, scenarios, transfer, qualityChecks } from './data.mjs';
import { initialDeckState, transition, visibleCalls } from './model.mjs';
import './token-profiler.css';
const state = ref(initialDeckState());
const running = ref(false);
let timer;
const currentCall = computed(() => calls[state.value.selectedCall]);
const choice = computed(() => scenarios[state.value.scenario]);
const stageLabels = ['Workflow', 'Usage', 'By call', 'Context', 'Attribution', 'Measurement', 'Redesign', 'Re-run', 'Verify', 'Transfer'];
const titles = [
  '一個 Coding Agent 完成這項任務，要呼叫模型幾次？', '162k 是怎麼來的？', '所以 Debug 就是最值得優化的地方嗎？',
  '這次 input 裡裝了什麼？', '把同一批 token 換個方式排列，會看到什麼？', '這些數字是怎麼量到的？',
  '要改哪一段系統結構？', '同一項任務，再跑一次。', 'Token 變少，品質也過關了嗎？', '換成 Data Analysis Agent，先改哪裡？'
];
const fmt = n => new Intl.NumberFormat('en-US').format(n);
const short = n => `${Number((n / 1000).toFixed(1))}k`;
function act(action, value) { if (running.value) stop(); state.value = transition(state.value, action, value); }
function stop() { clearInterval(timer); running.value = false; }
function run() {
  if (running.value) return;
  act('restart'); running.value = true;
  if (matchMedia('(prefers-reduced-motion: reduce)').matches) {
    for (let i = 0; i < workflow.length; i++) state.value = transition(state.value, 'runStep');
    running.value = false;
    return;
  }
  timer = setInterval(() => {
    state.value = transition(state.value, 'runStep');
    if (state.value.runStep === workflow.length - 1) stop();
  }, 430);
}
onUnmounted(stop);
function next() { act('next'); }
const rerunResult = computed(() => ({ before: scenarios.baseline, after: choice.value }));
</script>
<template>
<div class="tp-deck">
  <header class="tp-top"><a href="#/map" class="tp-exit">← 教材地圖</a><span class="tp-kicker">AGENT SYSTEM DESIGN / TOKEN PROFILER</span><span class="tp-synthetic">合成教學資料</span></header>
  <main class="tp-main">
    <div class="tp-heading"><p class="tp-overline">{{ String(state.stage + 1).padStart(2, '0') }} / 10　{{ stageLabels[state.stage] }}</p><h1>{{ titles[state.stage] }}</h1></div>
    <section v-if="state.stage === 0" class="tp-scene" aria-label="Coding Agent workflow">
      <div class="tp-task">TASK <strong>新增取消預約功能</strong></div>
      <div class="tp-workflow"><div v-for="(step, index) in workflow" :key="index" class="tp-step" :class="{ active: index === state.runStep, done: index < state.runStep, pending: index > state.runStep, failed: step === 'Test' && state.runStep >= index }"><span class="tp-index">{{ String(index + 1).padStart(2, '0') }}</span><strong>{{ step }}</strong><small v-if="step === 'Test' && state.runStep >= index">2 tests failed</small><small v-else-if="index <= state.runStep && step !== 'Test'">model call {{ workflow.slice(0, index + 1).filter(x => x !== 'Test').length }}</small></div></div>
      <div class="tp-bottomline"><span>TOOLS　Repository · Search · Editor · Test Runner</span><strong v-if="state.runStep >= 0">{{ state.runStep === 7 ? 'Run #184 completed' : '執行中' }}　·　{{ visibleCalls(state) }} model calls</strong></div>
      <button v-if="state.runStep < 7 && !running" class="tp-action" @click="run">執行任務 →</button><span v-if="running" class="tp-running" role="status">流程執行中…</span>
    </section>
    <section v-else-if="state.stage === 1" class="tp-scene tp-center" aria-label="總 token usage"><div class="tp-big-number"><span>7</span><small>MODEL CALLS</small></div><div class="tp-usage-line"><div><strong>{{ short(totals.input) }}</strong><span>input tokens</span></div><div class="tp-plus">＋</div><div><strong>{{ short(totals.output) }}</strong><span>output tokens</span></div></div><p class="tp-one-line">一次任務，由 7 次模型呼叫累積而成。</p></section>
    <section v-else-if="state.stage === 2" class="tp-scene" aria-label="每次模型呼叫"><div class="tp-call-chart"><button v-for="(call, index) in calls" :key="call.id" class="tp-call" :class="{ selected: state.selectedCall === index }" @click="act('call', index)" :aria-pressed="state.selectedCall === index"><span>{{ call.step }}</span><i :style="{ width: `${call.input / 37000 * 100}%` }"></i><b>{{ short(call.input) }}</b></button></div><div class="tp-inspector"><span>CALL {{ currentCall.id }} · {{ currentCall.step }} · model-x</span><strong>{{ fmt(currentCall.input) }} <small>input</small></strong><span>{{ fmt(currentCall.output) }} output　·　{{ currentCall.latency.toFixed(1) }}s</span></div></section>
    <section v-else-if="state.stage === 3" class="tp-scene" aria-label="單次 context composition"><div class="tp-context-head"><span>{{ currentCall.step.toUpperCase() }} / INPUT</span><strong>{{ fmt(currentCall.input) }} tokens</strong></div><div class="tp-stack" role="group" aria-label="選擇 context 來源"><button v-for="(source, index) in sources" :key="source.id" :style="{ flexGrow: currentCall.parts[index] }" :class="['tp-source-' + source.id, { selected: state.selectedSource === source.id }]" @click="act('source', source.id)" :aria-label="`${source.label} ${fmt(currentCall.parts[index])} tokens`" :aria-pressed="state.selectedSource === source.id"><span>{{ short(currentCall.parts[index]) }}</span></button></div><div class="tp-source-legend"><button v-for="source in sources" :key="source.id" :aria-pressed="state.selectedSource === source.id" @click="act('source', source.id)"><i :class="'tp-source-' + source.id"></i>{{ source.label }}</button></div><div v-if="state.selectedSource" class="tp-inspector tp-context-note"><span>{{ sources.find(s => s.id === state.selectedSource).label }}</span><strong>{{ sources.find(s => s.id === state.selectedSource).hint }}</strong><small>Context composition：模型這一次收到的輸入組成。</small></div></section>
    <section v-else-if="state.stage === 4" class="tp-scene" aria-label="Token attribution"><div class="tp-toggle"><button :aria-pressed="state.groupedBy === 'call'" @click="act('group', 'call')">By model call</button><button :aria-pressed="state.groupedBy === 'source'" @click="act('group', 'source')">By context source</button></div><div v-if="state.groupedBy === 'call'" class="tp-mass"><button v-for="(call,index) in calls" :key="call.id" @click="act('call',index)" :aria-pressed="state.selectedCall === index"><span>{{ call.step }}</span><i v-for="(part, i) in call.parts" :key="i" :class="'tp-source-' + sources[i].id" :style="{ flexGrow: part }"></i><b>{{ short(call.input) }}</b></button></div><div v-else class="tp-mass"><button v-for="source in sourceTotals" :key="source.id" @click="act('source',source.id)" :aria-pressed="state.selectedSource === source.id"><span>{{ source.label }}</span><i :class="'tp-source-' + source.id" :style="{ width: `${source.tokens / 58000 * 100}%` }"></i><b>{{ short(source.tokens) }}</b></button></div><div v-if="state.selectedSource === 'history' && state.groupedBy === 'source'" class="tp-history-strip"><span>同一段 history 被送往：</span><b v-for="(call,index) in calls.filter(c => c.parts[0] > 0)" :key="index">{{ call.step }}<small>{{ short(call.parts[0]) }}</small></b></div><p class="tp-one-line">{{ state.groupedBy === 'source' ? '最大單次：Debug #2，37k　／　最大累積來源：對話歷史，58k' : '切換成 By context source，看看七次呼叫累積的來源。' }}</p></section>
    <section v-else-if="state.stage === 5" class="tp-scene tp-measure" aria-label="量測與 instrumentation"><div class="tp-measure-row"><div class="tp-measure-node">Model call <span>model-x</span></div><div class="tp-arrow">→</div><div class="tp-measure-node tp-accent">Provider usage <span>input 37k / output 1.2k</span></div></div><div class="tp-fields">run_id　 step_id　 model　 input_tokens　 output_tokens　 latency</div><div class="tp-measure-row"><div class="tp-measure-node">Context Builder <span>組裝並標記來源</span></div><div class="tp-arrow">→</div><div class="tp-measure-node tp-accent">App instrumentation <span>history 16k / code 7k / …</span></div></div><div class="tp-fields">system　 task/spec　 history　 retrieved code　 tool results　 state　 other</div><p class="tp-one-line">模型 usage 記錄「用了多少」；應用程式在組裝 context 時記錄「從哪裡來」。</p></section>
    <section v-else-if="state.stage === 6" class="tp-scene" aria-label="架構重新設計"><div class="tp-options"><button :aria-pressed="state.scenario === 'baseline'" @click="act('scenario', 'baseline')">原始架構</button><button v-for="(item,id) in scenarios" :key="id" v-show="id !== 'baseline'" :aria-pressed="state.scenario === id" @click="act('scenario', id)">{{ item.label }}</button></div><div class="tp-architecture" :key="state.scenario"><template v-if="state.scenario === 'state'"><div class="tp-arch-inputs"><div>Artifacts / history <span>↓</span> Persistent state</div><div>Repository <span>↓</span> Relevant retrieval</div><div>Current task</div></div><div class="tp-arch-join">↘　↓　↙</div><div class="tp-arch-node tp-highlight">Context Builder</div><div class="tp-arch-join">↓</div><div class="tp-arch-node">Model</div></template><template v-else><div class="tp-arch-node">Task</div><div class="tp-arch-join">↓</div><div class="tp-arch-node">Agent</div><div class="tp-arch-join">↓</div><div class="tp-arch-node tp-highlight">{{ state.scenario === 'retrieval' ? 'Relevant files' : state.scenario === 'summary' ? 'Aggressive summary' : state.scenario === 'prompt' ? 'Shorter task/spec' : state.scenario === 'tools' ? 'Processed tool results' : state.scenario === 'validator' ? 'Deterministic validator' : state.scenario === 'model' ? 'Smaller model' : 'Full history + files + raw tool results + state' }}</div><div class="tp-arch-join">↓</div><div class="tp-arch-node">Model</div></template></div><p class="tp-one-line">影響來源：{{ sources.find(s => s.id === choice.focus)?.label || '模型選擇' }}　·　預估 input {{ short(choice.input) }}</p></section>
    <section v-else-if="state.stage === 7" class="tp-scene tp-center" aria-label="相同工作量重跑"><div class="tp-task">SAME TASK <strong>新增取消預約功能</strong></div><button v-if="!state.rerun" class="tp-action" @click="act('rerun')">Run same task →</button><div v-else class="tp-compare"><div><span>BEFORE</span><strong>{{ short(rerunResult.before.input) }}</strong><small>input tokens</small><p>{{ short(rerunResult.before.output) }} output　·　{{ rerunResult.before.latency }}s</p></div><div class="tp-compare-arrow">→</div><div><span>{{ choice.label }}</span><strong>{{ short(rerunResult.after.input) }}</strong><small>input tokens</small><p>{{ short(rerunResult.after.output) }} output　·　{{ rerunResult.after.latency }}s</p></div></div></section>
    <section v-else-if="state.stage === 8" class="tp-scene" aria-label="品質驗證"><div class="tp-verify-grid"><div class="tp-verify-head">同一套驗收基準 <span>{{ choice.label }}</span></div><div v-for="(check,index) in qualityChecks" :key="check" class="tp-check"><span>{{ check }}</span><b v-if="state.verified" :class="{ fail: choice.pass === false && index === 4 }">{{ choice.pass === false && index === 4 ? '未通過' : '通過' }}</b><b v-else>待檢查</b></div></div><button v-if="!state.verified" class="tp-action" @click="act('verify')">執行品質驗證 →</button><div v-else class="tp-verdict" :class="{ fail: !choice.pass }">{{ choice.pass === null ? '此方案仍需實測品質。' : choice.pass ? '品質基準保留，才可比較節省效果。' : '品質退步：取消預約必須保留原付款紀錄。' }}</div><div class="tp-alt"><button @click="act('scenario', 'state')" :aria-pressed="state.scenario === 'state'">狀態＋檢索</button><button @click="act('scenario', 'summary')" :aria-pressed="state.scenario === 'summary'">激進摘要：{{ short(scenarios.summary.input) }}</button></div></section>
    <section v-else class="tp-scene" aria-label="Data Analysis Agent transfer"><div class="tp-transfer-bar"><button v-for="item in transfer" :key="item.id" :style="{ flexGrow: item.share }" :class="{ selected: state.transferChoice === item.id }" @click="act('transfer',item.id)" :aria-label="`${item.label} ${item.share}%`"><strong>{{ item.share }}%</strong><span>{{ item.label }}</span></button></div><div class="tp-transfer-options"><button v-for="option in ['縮短 context', '較小模型', '優化查詢', '快取', '預先彙總']" :key="option" @click="act('transfer', option)" :aria-pressed="state.transferChoice === option">{{ option }}</button></div><p v-if="state.transferChoice" class="tp-one-line">{{ ['優化查詢','快取','預先彙總','warehouse'].includes(state.transferChoice) ? '資料倉儲查詢佔 61%。先處理這段瓶頸，再量測效果。' : '先看 profiler：LLM 只佔 18%，最大耗時在資料倉儲查詢。' }}</p><div class="tp-method">MEASURE → ATTRIBUTE → DIAGNOSE → REDESIGN → RE-RUN → VERIFY</div><p v-if="state.transferChoice" class="tp-one-line">先知道成本花在哪裡，再決定要改 prompt、context、workflow，還是 architecture。</p></section>
  </main>
  <footer class="tp-footer"><button @click="act('back')" :disabled="!state.history.length">← 返回</button><div class="tp-progress"><i v-for="index in 10" :key="index" :class="{ active: index - 1 === state.stage, past: index - 1 < state.stage }"></i></div><button @click="act('restart')">重新開始</button><button class="tp-next" @click="next" :disabled="state.stage === 9 || (state.stage === 0 && state.runStep < 7) || (state.stage === 6 && state.scenario === 'baseline') || (state.stage === 7 && !state.rerun) || (state.stage === 8 && !state.verified)">{{ state.stage === 9 ? '結束' : '下一步 →' }}</button></footer>
</div>
</template>
